apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app.dev
  namespace: example-app-dev
spec:
  dnsNames:
    - app.dev.example.com
  secretName: example-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
